import { Client, Account, Databases, ID, Query } from 'appwrite';
import { validateEnvVar } from '@/lib/utils/env';

const APPWRITE_URL = validateEnvVar('NEXT_PUBLIC_APPWRITE_URL', process.env.NEXT_PUBLIC_APPWRITE_URL);
const APPWRITE_PROJECT_ID = validateEnvVar('NEXT_PUBLIC_APPWRITE_PROJECT_ID', process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID);

export const client = new Client();

client
  .setEndpoint(APPWRITE_URL)
  .setProject(APPWRITE_PROJECT_ID);

export const account = new Account(client);
export const databases = new Databases(client);

export { ID, Query };

export const DATABASE_ID = validateEnvVar('NEXT_PUBLIC_APPWRITE_DATABASE_ID', process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID);

export const COLLECTIONS = {
  USERS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID || process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID || '66edc2d6002502837b8f',
  ACCOUNTS: process.env.NEXT_PUBLIC_APPWRITE_ACCOUNTS_COLLECTION_ID || '691e308b003297049b96',
  TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_TRANSACTIONS_COLLECTION_ID || '66edc32000303ca7660e',
  BUDGETS: process.env.NEXT_PUBLIC_APPWRITE_BUDGETS_COLLECTION_ID || '691e2552000757938b5b',
  SAVINGS_GOALS: process.env.NEXT_PUBLIC_APPWRITE_SAVINGS_GOALS_COLLECTION_ID || '691e25b6000f42bde800',
  TRANSFERS: process.env.NEXT_PUBLIC_APPWRITE_TRANSFERS_COLLECTION_ID || '691e25f20031423a6b93',
  AI_SUGGESTIONS: process.env.NEXT_PUBLIC_APPWRITE_AI_SUGGESTIONS_COLLECTION_ID || '691e2641000724c97847',
  BANKS: process.env.NEXT_PUBLIC_APPWRITE_BANKS_COLLECTION_ID || '66edc354001142d6105b',
};
